# Configure REST Client in Visual Studio Code:
# Open your Visual Studio Code settings for the current workspace (Ctrl + , or Cmd + ,).
# Add a setting to reference the configuration file:
#   "rest-client.environmentVariables": {
#     "$shared": {
#         "HOST_ADDRESS_LOCAL": "http://localhost:54321/functions/v1/tickets",
#         "HOST_ADDRESS_STAGE": "https://xxxxxxxxxx.supabase.co/functions/v1/tickets",
#         "SUPABASE_TOKEN_LOCAL": "xxxxxxx",
#         "SUPABASE_TOKEN_STAGE": "xxxxxxx"
#     }
#   }

@HOST_ADDRESS = {{HOST_ADDRESS_LOCAL}}
@SUPABASE_TOKEN = {{SUPABASE_TOKEN_LOCAL}}
# @HOST_ADDRESS = {{HOST_ADDRESS_STAGE}}
# @SUPABASE_TOKEN = {{SUPABASE_TOKEN_STAGE}}

GET {{HOST_ADDRESS}}/iataCode/SDU HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{SUPABASE_TOKEN}}


POST {{HOST_ADDRESS}}  HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{SUPABASE_TOKEN}}

{
    "quote_id":103,
    "price":910,
    "direct":true,
    "quote_date_time":"2024-01-20 14:19:02.000 -0300",
    "outbound_leg":[{"iataCode": "SDU", "placeName": "Rio de Janeiro", "carrierName": "Azul", "departureDate": "2024-08-04T17:30"}], 
    "inbound_leg":[{"iataCode": "EZE", "placeName": "Buenos Aires", "carrierName": "Azul", "departureDate": "2024-08-09T07:00"}],
    "image":"/amsterdam-buildings-6778915_640.jpg"
}

PUT {{HOST_ADDRESS}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{SUPABASE_TOKEN}}

{
    "id":3,
    "price":941,
    "direct":false
}

DELETE {{HOST_ADDRESS}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{SUPABASE_TOKEN}}

{
    "id":5
}
